<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'G403TempRoleProvider\Module'                        => __DIR__ . '/Module.php',
	'G403TempRoleProvider\Controller\SkeletonController' => __DIR__ . '/src/G403TempRoleProvider/Controller/SkeletonController.php',
	'G403TempRoleProvider\Framework\TestCase'            => __DIR__ . '/tests/G403TempRoleProvider/Framework/TestCase.php',
	'G403TempRoleProvider\SampleTest'                    => __DIR__ . '/tests/G403TempRoleProvider/SampleTest.php',
);